import time
import asyncio
import aiohttp
import threading
import os
from http.server import BaseHTTPRequestHandler, HTTPServer

# --- FAKE WEB SERVER TO KEEP RENDER HAPPY ---
class DummyHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/plain; charset=utf-8')
        self.end_headers()
        self.wfile.write("FORB1D Bot is running at LIGHTSPEED! 👽🚀".encode('utf-8'))

def keep_alive():
    port = int(os.environ.get("PORT", 10000))
    server = HTTPServer(('0.0.0.0', port), DummyHandler)
    print(f"✅ Web port {port} opened! Render is happy.")
    server.serve_forever()


# --- YOUR FIREBASE CODE (NOW ASYNC) ---
DATABASE_URL = "https://spammerachatv4-default-rtdb.asia-southeast1.firebasedatabase.app/global_chats.json"

async def send_message(session, message_text):
    """Sends a single request using the shared high-speed connection pool."""
    payload = {
        "username": "FORB1D🔥",
        "displayName": "SYSTEM_OVERRIDE",
        "message": message_text,
        "jobIdLocation": "Render_Cloud_Hyperdrive",
        "timestamp": int(time.time())
    }
    
    try:
        # We use a 5-second timeout because async requests can pile up
        async with session.post(DATABASE_URL, json=payload, timeout=5) as response:
            if response.status == 200:
                print("🔥 [SPEED] Message injected!")
            elif response.status == 429:
                print("🛑 CAUTION: Firebase is rate-limiting us (429)! Going too fast!")
            else:
                print(f"❌ Failed: {response.status}")
    except Exception as e:
        print(f"❌ Network drop: {e}")


async def hyper_loop():
    """The main asynchronous infinite loop."""
    output_text = " 🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱🔱 FORBID THE BEST HACKER 🔱 "
    print("🚀 Starting ASYNC execution loop...")
    
    # ClientSession keeps the TCP connection alive, making it massively faster
    async with aiohttp.ClientSession() as session:
        while True:
            # asyncio.create_task fires the request into the background instantly
            asyncio.create_task(send_message(session, output_text))
            
            # The throttle. 
            # 0.1 = 10 requests/sec. 
            # 0.05 = 20 requests/sec. 
            # 0 = MAXIMUM OVERDRIVE (Will likely crash Render or get IP banned)
            await asyncio.sleep(0.00001) 


# --- EXECUTION FLOW ---
if __name__ == "__main__":
    # 1. Start the fake web server
    threading.Thread(target=keep_alive, daemon=True).start()
    
    # 2. Start the high-speed async loop
    try:
        asyncio.run(hyper_loop())
    except KeyboardInterrupt:
        print("Loop stopped.")
